# API documentation configuration
springdoc:
  show-actuator: true
  packagesToScan: com.homework.employeetracker
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: method
    path: /

# Database configuration
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    com.homework.employeetracker: DEBUG